name = "mini-notes"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
kv_namespaces = [
  { binding = "NOTES", id = "your-notes-kv-id", preview_id = "your-notes-kv-preview-id" },
  { binding = "USERS", id = "your-users-kv-id", preview_id = "your-users-kv-preview-id" }
]

[env.development]
kv_namespaces = [
  { binding = "NOTES", id = "your-notes-kv-dev-id", preview_id = "your-notes-kv-dev-preview-id" },
  { binding = "USERS", id = "your-users-kv-dev-id", preview_id = "your-users-kv-dev-preview-id" }
]